platform:
  - x64

environment:
  COMPOSER_NO_INTERACTION: 1
  ANSICON: "121x90 (121x90)"
  DEPS: high

init:
  - ps: if ($Env:APPVEYOR_REPO_TAG_NAME -eq $null ) { $Env:COMPOSER_ROOT_VERSION = "dev-master" }
  - ps: $Env:Path += ";C:\php"

# Cache PHP and tooling
cache:
  # The C:\Downloads directory will be used as a storage for downloaded archives.
  # So you may want to cache it.
  - 'C:\Downloads -> .appveyor.yml'
  - '%LOCALAPPDATA%\Composer\files'
  - '%LOCALAPPDATA%\Composer\vcs'

install:
  # Download php-appveyor.psm1 module and invoke it to the current session
  - ps: (new-object Net.WebClient).DownloadString("https://raw.githubusercontent.com/sergeyklay/php-appveyor/1.3.0/php-appveyor.psm1") | iex

  - ps: InstallPhp -Version "8.0" -BuildType "nts-Win32" -VC 16 -Platform $Env:PLATFORM
  - ps: EnablePhpExtension -Name "curl"
  - ps: EnablePhpExtension -Name "openssl"
  - ps: EnablePhpExtension -Name "mbstring"
  - ps: EnablePhpExtension -Name "fileinfo"
  - ps: Write-Output "zend.assertions=1" | Out-File -Encoding "ASCII" -Append "C:\php\php.ini"
  - ps: Write-Output "assert.exception=On" | Out-File -Encoding "ASCII" -Append "C:\php\php.ini"
  - ps: Write-Output "error_reporting=E_ALL" | Out-File -Encoding "ASCII" -Append "C:\php\php.ini"
  - ps: php -r "phpinfo(INFO_GENERAL);"
  - ps: InstallComposer

build_script:
  # PowerShell treats *any* output to stderr as error so we need to run composer update with cmd instead
  - ps: if ($Env:DEPS -eq "low") { $Env:DEPS_FLAGS = "--prefer-lowest --prefer-stable" }
  - ps: if ($Env:DEPS -eq "high") { $Env:DEPS_FLAGS = "" }
  - composer update %DEPS_FLAGS% --no-progress
  - ps: ls -l vendor/bin

## Run the actual test
test_script:
  - ps: vendor/bin/composer-require-checker
  - ps: vendor/bin/psalm --shepherd
  - ps: vendor/bin/phpunit
